{
  "White": "#ffffff",
  "ColorRamp": {
    "AS Greys": {
      "AS Greys 100": "#e1e1e1",
      "AS Greys 200": "#b2b2b2",
      "AS Greys 300": "#a1a1a1",
      "AS Greys 400": "#939393",
      "AS Greys 500": "#848484",
      "AS Greys 600": "#686868",
      "AS Greys 700": "#555555",
      "AS Greys 800": "#454545",
      "AS Greys 900": "#383838",
      "AS Greys 1000": "#1c1c1c"
    },
    "Sally Red": {
      "Sally Red 100": "#ffd8e0",
      "Sally Red 200": "#ff92a7",
      "Sally Red 300": "#ff738e",
      "Sally Red 400": "#ff5677",
      "Sally Red 500": "#ff254f",
      "Sally Red 600": "#d10029",
      "Sally Red 700": "#ae0022",
      "Sally Red 800": "#8e001c",
      "Sally Red 900": "#770017",
      "Sally Red 1000": "#42000d"
    },
    "OYA Olive": {
      "OYA Olive 100": "#e1e3dd",
      "OYA Olive 200": "#b0b4a5",
      "OYA Olive 300": "#9ea391",
      "OYA Olive 400": "#919681",
      "OYA Olive 500": "#818770",
      "OYA Olive 600": "#656a58",
      "OYA Olive 700": "#535748",
      "OYA Olive 800": "#42453a",
      "OYA Olive 900": "#373930",
      "OYA Olive 1000": "#1c1d18"
    },
    "OYA Earth": {
      "OYA Earth 100": "#efdfd8",
      "OYA Earth 200": "#d3aa95",
      "OYA Earth 300": "#c8967c",
      "OYA Earth 400": "#c08669",
      "OYA Earth 500": "#b77452",
      "OYA Earth 600": "#925a3d",
      "OYA Earth 700": "#784a32",
      "OYA Earth 800": "#603b28",
      "OYA Earth 900": "#4f3121",
      "OYA Earth 1000": "#281911"
    }
  },
  "OYA": {
    "Olive": "#6b705d",
    "Camel": "#ca9980"
  },
  "fontFamilies": {
    "poppins": "Poppins"
  },
  "lineHeights": {
    "0": "94%",
    "1": "110%",
    "2": "93%",
    "3": "97%",
    "4": "98.5%",
    "5": "100%",
    "6": "128%",
    "7": "140%",
    "8": "104.5%",
    "9": "130%",
    "10": "98.5%",
    "11": "82.5%",
    "12": "115.5%"
  },
  "fontWeights": {
    "poppins-0": "Bold",
    "poppins-1": "SemiBold",
    "poppins-2": "Regular",
    "poppins-3": "ExtraLight"
  },
  "fontSize": {
    "0": "10",
    "1": "12",
    "2": "14",
    "3": "16",
    "4": "18",
    "5": "20",
    "6": "22",
    "7": "24",
    "8": "26",
    "9": "28",
    "10": "30",
    "11": "32",
    "12": "34",
    "13": "36",
    "14": "38",
    "15": "40",
    "16": "42",
    "17": "44",
    "18": "48",
    "19": "56",
    "20": "60",
    "21": "62",
    "22": "64",
    "23": "72",
    "24": "85",
    "25": "94",
    "26": "96",
    "27": "128"
  },
  "letterSpacing": {
    "0": "1%",
    "1": "-3%",
    "2": "-1%",
    "3": "-0.5%",
    "4": "-2%",
    "5": "0%"
  },
  "paragraphSpacing": {
    "0": "8",
    "1": "32"
  },
  "Bold": {
    "B14": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "94%",
      "fontSize": "128",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "B13": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "94%",
      "fontSize": "96",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "B125": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "94%",
      "fontSize": "94",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "B12": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "94%",
      "fontSize": "72",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "B11": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "94%",
      "fontSize": "60",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "B115": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "94%",
      "fontSize": "64",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "B105": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "94%",
      "fontSize": "56",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "B10": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "94%",
      "fontSize": "48",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "B9": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "94%",
      "fontSize": "44",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "B8": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "110%",
      "fontSize": "42",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "B7": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "110%",
      "fontSize": "40",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "B6": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "110%",
      "fontSize": "38",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "B5": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "110%",
      "fontSize": "36",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "B4": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "110%",
      "fontSize": "34",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "B3": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "110%",
      "fontSize": "32",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "B2": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "110%",
      "fontSize": "30",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "B1": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "110%",
      "fontSize": "28",
      "letterSpacing": "-3%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "BS": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "110%",
      "fontSize": "26",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "BXS": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "110%",
      "fontSize": "24",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "BXS1": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "110%",
      "fontSize": "22",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "BXS2": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "110%",
      "fontSize": "20",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "BXS3": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "110%",
      "fontSize": "18",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "BXS4": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "110%",
      "fontSize": "16",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "BXS5": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "110%",
      "fontSize": "14",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "BXS6": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "110%",
      "fontSize": "12",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "BXS7": {
      "fontFamily": "Poppins",
      "fontWeight": "Bold",
      "lineHeight": "110%",
      "fontSize": "10",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "Display": {
    "D14": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "94%",
      "fontSize": "128",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "D125": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "94%",
      "fontSize": "94",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "D12": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "94%",
      "fontSize": "72",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "D115": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "94%",
      "fontSize": "62",
      "letterSpacing": "-3%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "D11": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "94%",
      "fontSize": "56",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "D10": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "94%",
      "fontSize": "48",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "D9": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "94%",
      "fontSize": "44",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "D8": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "110%",
      "fontSize": "42",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "D7": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "110%",
      "fontSize": "40",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "D6": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "110%",
      "fontSize": "38",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "D5": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "110%",
      "fontSize": "36",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "D4": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "110%",
      "fontSize": "34",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "D3": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "110%",
      "fontSize": "32",
      "letterSpacing": "-1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "D2": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "110%",
      "fontSize": "30",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "D1": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "93%",
      "fontSize": "28",
      "letterSpacing": "-1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "DS": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "97%",
      "fontSize": "26",
      "letterSpacing": "-3%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "DXS": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "98.5%",
      "fontSize": "24",
      "letterSpacing": "-0.5%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "DXS1": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "98.5%",
      "fontSize": "22",
      "letterSpacing": "-3%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "DXS2": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "110%",
      "fontSize": "20",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "DXS3": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "100%",
      "fontSize": "18",
      "letterSpacing": "-2%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "DXS5": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "110%",
      "fontSize": "14",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "DXS4": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "110%",
      "fontSize": "16",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "DXS6": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "110%",
      "fontSize": "12",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "DXS7": {
      "fontFamily": "Poppins",
      "fontWeight": "SemiBold",
      "lineHeight": "110%",
      "fontSize": "10",
      "letterSpacing": "1%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "Regular": {
    "R14": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "128%",
      "fontSize": "128",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "R13": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "128%",
      "fontSize": "96",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "R125": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "128%",
      "fontSize": "85",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "R12": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "140%",
      "fontSize": "72",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "R11": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "140%",
      "fontSize": "60",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "R10": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "140%",
      "fontSize": "48",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "R9": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "140%",
      "fontSize": "44",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "R8": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "140%",
      "fontSize": "42",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "R7": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "140%",
      "fontSize": "40",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "R6": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "140%",
      "fontSize": "38",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "R5": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "140%",
      "fontSize": "36",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "R4": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "140%",
      "fontSize": "34",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "R3": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "140%",
      "fontSize": "32",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "R2": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "140%",
      "fontSize": "30",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "R1": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "140%",
      "fontSize": "28",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "RS": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "140%",
      "fontSize": "26",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "RXS": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "140%",
      "fontSize": "24",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "RXS1": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "140%",
      "fontSize": "22",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "RXS2": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "104.5%",
      "fontSize": "20",
      "letterSpacing": "-3%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "RXS3": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "130%",
      "fontSize": "18",
      "letterSpacing": "0%",
      "paragraphSpacing": "8",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "RXS4": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "98.5%",
      "fontSize": "16",
      "letterSpacing": "0%",
      "paragraphSpacing": "8",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "RXS5": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "130%",
      "fontSize": "14",
      "letterSpacing": "0%",
      "paragraphSpacing": "8",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "RXS6": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "130%",
      "fontSize": "12",
      "letterSpacing": "0%",
      "paragraphSpacing": "8",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "RXS7": {
      "fontFamily": "Poppins",
      "fontWeight": "Regular",
      "lineHeight": "130%",
      "fontSize": "10",
      "letterSpacing": "0%",
      "paragraphSpacing": "8",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "Light": {
    "L14": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "128%",
      "fontSize": "128",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "L13": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "128%",
      "fontSize": "96",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "L125": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "82.5%",
      "fontSize": "85",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "L12": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "140%",
      "fontSize": "72",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "L11": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "140%",
      "fontSize": "60",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "L10": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "140%",
      "fontSize": "48",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "L9": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "140%",
      "fontSize": "44",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "L8": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "140%",
      "fontSize": "42",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "L7": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "140%",
      "fontSize": "40",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "L6": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "140%",
      "fontSize": "38",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "L5": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "140%",
      "fontSize": "36",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "L4": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "140%",
      "fontSize": "34",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "L3": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "140%",
      "fontSize": "32",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "L2": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "140%",
      "fontSize": "30",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "L1": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "140%",
      "fontSize": "28",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "LS": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "140%",
      "fontSize": "26",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "LXS": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "140%",
      "fontSize": "24",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "LXS1": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "140%",
      "fontSize": "22",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "LXS2": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "115.5%",
      "fontSize": "20",
      "letterSpacing": "0%",
      "paragraphSpacing": "32",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "LXS3": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "130%",
      "fontSize": "18",
      "letterSpacing": "0%",
      "paragraphSpacing": "8",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "LXS4": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "130%",
      "fontSize": "16",
      "letterSpacing": "0%",
      "paragraphSpacing": "8",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "LXS5": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "130%",
      "fontSize": "14",
      "letterSpacing": "0%",
      "paragraphSpacing": "8",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "LXS6": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "130%",
      "fontSize": "12",
      "letterSpacing": "0%",
      "paragraphSpacing": "8",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    },
    "LXS7": {
      "fontFamily": "Poppins",
      "fontWeight": "ExtraLight",
      "lineHeight": "130%",
      "fontSize": "10",
      "letterSpacing": "0%",
      "paragraphSpacing": "8",
      "paragraphIndent": "0px",
      "textCase": "none",
      "textDecoration": "none"
    }
  },
  "textCase": {
    "none": "none"
  },
  "textDecoration": {
    "none": "none"
  },
  "paragraphIndent": {
    "0": "0px"
  }
}
